### ISSUE TITLE
Compilation failure after package rename

### ISSUE THREAD

**Issue by GULPF** [JohnAD/jesterwithplugins#7]
Since the rename to `jesterwithplugins` compilation fails with `jesterwithplugins.nim(8, 22) Error: cannot open file: jester/private/errorpages`. I'm guessing all the internal imports must be changed to `import jesterwithplugins/...`?

**Comment by JohnAD** [comment]
I could not reproduce the error on my machine, but the directory reference of "jester" could cause odd conflicts on machines with both libraries installed.

So, I've renamed all internal references. And, while I was at it, I moved the source code to a "src" subdirectory which I believe is more in-line with current nimble advice.

@GULPF Does this most recent commit work better? If it does, I'll roll these changes into new release.

**Comment by GULPF** [comment]
> And, while I was at it, I moved the source code to a "src" subdirectory which I believe is more in-line with current nimble advice.

I think this change caused another breakage. I now get:

`/root/.nimble/pkgs/jesterwithplugins-#head/jesterwithplugins.nim(78, 30) Error: cannot open file: ../jesterwithplugins.nimble`

I believe this happens because Nimble doesn't include the `src` folder itself when installing a package (the content of the folder is moved to the package root), so the path to the .nimble file will be different after installation.

**Comment by JohnAD** [comment]
My bad, I should have checked both the local `nimble develop` and the `nimble install jesterwithplugins` scenarios.

I've upgraded the release version to 0.5.2 and the library no longer attempts to read it's own nimble file. It's not as "pretty" but it works more universally now.

Thanks!

**Comment by GULPF** [comment]
Thank you, it now seems to work :)
